name: Build Release CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}

      - name: Docker Buildx Argo workflow
        env:
          DOCKERIO_ORG: quay.io/numaio
          PLATFORM: linux/x86_64
          TARGET: numaflow-sink/argo-workflow
        run: |
          tag=$(basename $GITHUB_REF)
          if [ $tag = "master" ]; then
            tag="latest"
          fi
          
          image_name="${DOCKERIO_ORG}/numaflow-sink/argo-workflow:${tag}"
          
          cd argo-workflow
          docker buildx build \
            --output "type=image,push=true" \
            --platform="${PLATFORM}" \
            --tag $image_name .
            
      - name: Docker Buildx HTTP Sink
        env:
          DOCKERIO_ORG: quay.io/numaio
          PLATFORM: linux/x86_64
        run: |
          tag=$(basename $GITHUB_REF)
          if [ $tag = "master" ]; then
            tag="latest"
          fi
          image_name="${DOCKERIO_ORG}/numaflow-sink/http-sink:${tag}"
          
          cd http-sink
          docker buildx build \
            --output "type=image,push=true" \
            --platform="${PLATFORM}" \
            --tag $image_name .
            
      - name: Docker Buildx Prometheus-pusher
        env:
          DOCKERIO_ORG: quay.io/numaio
          PLATFORM: linux/x86_64
        run: |
          tag=$(basename $GITHUB_REF)
          if [ $tag = "master" ]; then
            tag="latest"
          fi
          image_name="${DOCKERIO_ORG}/numaflow-sink/prometheus-pusher:${tag}"
          
          cd prometheus-pusher
          docker buildx build \
            --output "type=image,push=true" \
            --platform="${PLATFORM}" \
            --tag $image_name .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            $(basename $GITHUB_REF) has been released. 
            Argo-workflow : quay.io/numaio/numaflow-sink/argo-workflow:${{ github.ref }}
            Http-sink  : quay.io/numaio/numaflow-sink/http-sink:${{ github.ref }}
            Pormetheus-Pusher: quay.io/numaio/numaflow-sink/prometheus-pusher:${{ github.ref }}
          draft: false
          prerelease: false
